### ISSUE TITLE
Error in "eofsAsCorrelation"  'numpy.ndarray' object has no attribute 'filled'

### ISSUE THREAD

**Issue by scott-hosking** [ajdawson/eofs#37] opened 2015-12-10 13:25 UTC
Hi, I've just found the following error after trying your iris example using my own cube.  I'm using numpy version '1.10.1'

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/home/scott/Copy/WORK/WIP/ASL_SOM_vs_EOF/EOF/asl_eof.py in <module>()
     18 # PC time series and the input SST anomalies at each grid point, and the
     19 # leading PC time series itself.
---> 20 eof1 = solver.eofsAsCorrelation(neofs=1)
     21 pc1 = solver.pcs(npcs=1, pcscaling=1)
     22 

/home/scott/PYTHON/eofs/iris.pyc in eofsAsCorrelation(self, neofs)
    288 
    289         """
--> 290         eofs = self._solver.eofsAsCorrelation(neofs)
    291         eofdim = DimCoord(range(eofs.shape[0]),
    292                           var_name='eof',

/home/scott/PYTHON/eofs/standard.pyc in eofsAsCorrelation(self, neofs)
    364         # numpy array filled with numpy.nan.
    365         if not self._filled:
--> 366             c = c.filled(fill_value=np.nan)
    367         return c
    368 

AttributeError: 'numpy.ndarray' object has no attribute 'filled'

**Comment by ajdawson** [comment] 2015-12-10 13:33
See #34. This is a regression in numpy (numpy/numpy#6611) which should be fixed in v1.10.2 which is currently only a release candidate. I haven't had time to put a workaround in eofs, and I'm not sure I will since this is already fixed in numpy...

**Closed** 2015-12-10 13:54 UTC

**Comment by ajdawson** [comment] 2015-12-10 13:56
@scott-hosking - I put a workaround in eofs, the master branch has this fix. Is that sufficient for you for now, or do you need a new release/conda package?

**Comment by scott-hosking** [comment] 2015-12-10 14:04
@ajdawson, thank you! I'm currently using your conda package but I'm happy to add this workaround myself for now and wait for your next release.

**Comment by ajdawson** [comment] 2015-12-10 15:24
I've released v0.5.1 and made conda packages for 64-bit Linux. You should be able to do `conda update -c ajdawson eofs` to upgrade.

**Comment by scott-hosking** [comment] 2015-12-10 16:07
That worked! thank you
